USE [master]
GO

/****** Object:  Database [CurrencyExchange]    Script Date: 01.11.2023 19:54:29 ******/
CREATE DATABASE [CurrencyExchange]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CurrencyExchange', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CurrencyExchange.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CurrencyExchange_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CurrencyExchange_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CurrencyExchange].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CurrencyExchange] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CurrencyExchange] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CurrencyExchange] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CurrencyExchange] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CurrencyExchange] SET ARITHABORT OFF 
GO

ALTER DATABASE [CurrencyExchange] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CurrencyExchange] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CurrencyExchange] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CurrencyExchange] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CurrencyExchange] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CurrencyExchange] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CurrencyExchange] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CurrencyExchange] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CurrencyExchange] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CurrencyExchange] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CurrencyExchange] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CurrencyExchange] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CurrencyExchange] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CurrencyExchange] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CurrencyExchange] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CurrencyExchange] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CurrencyExchange] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CurrencyExchange] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CurrencyExchange] SET  MULTI_USER 
GO

ALTER DATABASE [CurrencyExchange] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CurrencyExchange] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CurrencyExchange] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CurrencyExchange] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CurrencyExchange] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CurrencyExchange] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CurrencyExchange] SET QUERY_STORE = ON
GO

ALTER DATABASE [CurrencyExchange] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CurrencyExchange] SET  READ_WRITE 
GO

