//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Class.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurseCurrencie
    {
        public int ID { get; set; }
        public decimal CourseUSD { get; set; }
    
        public virtual TypesCurrencies TypesCurrencies { get; set; }
    }
}
