//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Class.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int IdEmployee { get; set; }
        public string NameEmployee { get; set; }
        public string FamilyEmployee { get; set; }
        public string Role { get; set; }
        public string CurrencyEmployee { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual TypesCurrencies TypesCurrencies { get; set; }
    }
}
